cloud:
    id: os
    type: OpenStack
    host: my_cloud_endpoint
    # e.g. host: http://openstack.fisica.unipg.it:5000/ 
    username: my_username
    password: < PUT HERE YOUR OpenStack Password >
    tenant: my_os_tenant
    auth_version: 3.x_password
    domain: default
im:
    id: im
    type: InfrastructureManager
    host: https://im-dodas.cloud.cnaf.infn.it/infrastructures 
    token: < PUT HERE YOUR IAM TOKEN > 

